#!/bin/bash
# Rustclaw — what it is and how to use it
# Run this to verify the installation works.

set -euo pipefail

echo "=== Rustclaw ==="
echo ""
echo "A complete Rust agent runtime. Type 'agenticlaw' to chat with Claude Opus 4.6 (1M context)."
echo ""
echo "Repository: https://github.com/thomcom/agentiagency.git"
echo "Branch: ws2-3-agency"
echo "Worktree: /home/devkit/worktrees/ws2-3-agency/agenticlaw"
echo ""
echo "=== Commands ==="
echo "  agenticlaw           — launch vim-mode TUI chat (default)"
echo "  agenticlaw -r        — resume latest .ctx session"
echo "  agenticlaw gateway   — web portal at http://localhost:18789"
echo "  agenticlaw version   — show version"
echo ""
echo "=== Architecture ==="
echo "Cargo workspace with 6 crates:"
echo "  agenticlaw-core      — types, protocol, errors"
echo "  agenticlaw-llm       — Anthropic SSE streaming client"
echo "  agenticlaw-tools     — modular tools (bash, read, write, edit, glob, grep)"
echo "  agenticlaw-agent     — AgentRuntime, Session, .ctx persistence"
echo "  agenticlaw-gateway   — axum WebSocket server, vim TUI, CLI"
echo "  agenticlaw (root)    — .ctx format viewer (agenticlaw-fmt binary)"
echo ""
echo "=== .ctx Format ==="
echo "Source of truth for sessions. Plain text, human-readable."
echo "  <up> tags = input to model (user + tool results)"
echo "  Bare text = model output"
echo "  --- <timestamp> --- separators"
echo "  Files: .agenticlaw/sessions/<YYYYMMDD-HHMMSS>-<id>.ctx"
echo ""
echo "=== Key Features ==="
echo "  - Auto-loads SOUL.md/AGENTS.md from workspace"
echo "  - Every turn persists to .ctx files on disk"
echo "  - 6 modular tools (one file each in crates/agenticlaw-tools/src/tools/)"
echo "  - ESC cancels running agent operations"
echo "  - Vim keybindings: i/a/A/I/o, hjkl, w/b, x, d, Enter sends, q quits"
echo "  - Status bar: vim mode, model, session id, context usage"
echo "  - Web portal serves .ctx at /ctx/{session}"
echo "  - 211+ tests including real Anthropic API integration"
echo "  - Zero compiler warnings"
echo ""
echo "=== Build & Test ==="
echo "  cd /home/devkit/worktrees/ws2-3-agency/agenticlaw"
echo "  source ~/.keys.sh  # ANTHROPIC_API_KEY"
echo "  cargo build --workspace"
echo "  cargo test --workspace"
echo "  cargo install --path crates/agenticlaw-gateway --force"
echo ""
echo "=== Verify ==="

if command -v agenticlaw &>/dev/null; then
    echo "agenticlaw binary: $(which agenticlaw)"
    echo "OK"
else
    echo "agenticlaw not installed. Run: cargo install --path crates/agenticlaw-gateway"
fi
